import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'
import { InputText } from 'primereact/inputtext';
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';
import 'primereact/resources/primereact.css';
import { Badge } from 'primereact/badge';
import { Toast } from 'primereact/toast';
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [movieList, setMovieList] = useState([])
  useEffect(() => {
    fetch("https://api.themoviedb.org/3/search/movie?api_key=36959670b59d486d71b022b7cb1c7a4a&query=a")
      .then((response) => (response.json()))
      .then((json) => {
        setMovieList(json.results);
        localStorage.setItem("movies", JSON.stringify(json.results))
      });
    setMovieCart(JSON.parse(localStorage.getItem("cart")))
  }, [])

  const [movieCart, setMovieCart] = useState([])
  const addCart = (val) => {
    const movies = [...movieCart, val]
    setMovieCart(movies)
    showSuccess(val.name)
    localStorage.setItem("cart", JSON.stringify(movies))
  }

  const toast = useRef(null);
  const showSuccess = (title) => {
    toast.current.show({
      severity: 'info',
      summary: `${title.length > 28 ? title.slice(0, 28) + "..." : title}`,
      detail: 'add to you cart',
      life: 3456
    });
  }

  const [valSearch, setValSearch] = useState("")

  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='page-index'>
        <Toast ref={toast} position="top-right" />

        <div id="btn"
          className={styles.thirteen} style={{ width: "3.2em", height: "2em", float: "right", margin: "10px", cursor: "pointer" }}
        >
          <i className="pi pi-shopping-cart icon" />
          {movieCart.length > 0 &&
            <Badge value={movieCart.length}
              style={{
                position: "absolute",
                top: "2px",
                right: "2px"
              }}
            />
          }
        </div>
        <h2 style={{ paddingTop: "20px", paddingLeft: "30px" }}>
          Movie Shop
        </h2>
        <div className={styles.center}>
          <span className="p-input-icon-right box-search">
            <i className="pi pi-search" />
            <InputText
              // value={}  
              onChange={e => setValSearch(e.target.value)}
              onKeyDown={(e) => {
                if (e.key == "Enter") {
                  const lists = []
                  movieList.find(ele => {
                    if (ele.title.toLowerCase().includes(e.target.value.toLowerCase())) {
                      lists.push(ele)
                    }
                  })
                  setMovieList(lists)
                }
                if (!valSearch) {
                  setMovieList(JSON.parse(localStorage.getItem("movies")))
                }
              }}
              placeholder="Search" />
          </span>
        </div>

        <div style={{ textAlign: "center" }}>
          {movieList?.map((ele, i) => (
            <div className='card-movie'>
              <div
                style={{
                  backgroundImage: `url(https://image.tmdb.org/t/p/w200${ele.poster_path})`,
                  width: "200px",
                  height: "200px",
                  borderRadius: "6px",
                  marginBottom: "10px",
                  margin: "auto"
                }}
              />
              <p>
                {ele.title}
              </p>
              <div className='cart'
                onClick={() => addCart({ name: ele.title, price: 100 })}>
                <div style={{ width: "70%", display: "inline-block" }}>
                  100
                  {/* on your cart */}
                </div>
                <i className="pi pi-shopping-cart icon" />
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}
